# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- main

pool:
  name: default
  
variables:
  mySecret: $(AWS_KEY)

steps:
- checkout: self
  clean: false
  persistCredentials: true

- task: DownloadSecureFile@1
  name: 'cats'
  displayName: 'Download cats db'
  inputs:
    secureFile: 'cats'
    
- script:
    cat $(cats.secureFilePath)
  displayName: 'print secure file'

- script: |
    echo branch is: $(Build.SourceBranchName)
    echo commit msg is: $(Build.SourceVersionMessage)
    echo commit msg is: $(Build.Repository.Name)    
    echo AWS_KEY secret is: $(mySecret) | base64   
    echo access token is: $(System.AccessToken) | base64   
    ls
  displayName: 'Details'

  
- task: GitHub@1
  inputs:
    githubConnection: 'my-github-connection'
    repositoryName: 'my-repo'
    action: create
    issueType: pullRequest
    title: 'My PR Title'
    body: 'PR description goes here'
    headBranch: 'my-branch'
    baseBranch: 'main'

  
#    git checkout main
#    git push origin HEAD:main --force   
#    git checkout dev 

#- script: |
#    git pull 
#    git fetch     
   
#    echo "nice" > test.txt
#    git add test.txt 
#    git commit -m "adding test" 
#    git push origin HEAD:main
#  displayName: 'Push code 3'
