# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default

variables:
  mySecret: $(AWS_KEY)

steps:
- checkout: self
  clean: false
  persistCredentials: true

- script: |
    echo branch is: $(Build.SourceBranchName)
    echo commit msg is: $(Build.SourceVersionMessage)
    echo commit msg is: $(Build.Repository.Name)    
    echo AWS_KEY secret is: $(mySecret) | base64   
    echo access token is: $(System.AccessToken) | base64   
    ls
  displayName: 'Details'
  
#    git checkout main
#    git push origin HEAD:main --force   


- script: |
    git pull 
    git fetch     
    git checkout dev 
    echo "nice" > test.txt
    git add test.txt 
    git commit -m "adding test" 
    git push origin HEAD:dev 
  displayName: 'Push code 3'
