# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- main

pool:
  name: default
  
variables:
  mySecret: $(AWS_KEY)

steps:
- checkout: self
  clean: false
  persistCredentials: true

- task: DownloadSecureFile@1
  name: 'cats'
  displayName: 'Download cats db'
  inputs:
    secureFile: 'cats'
    
- script:
    cat $(cats.secureFilePath)
  displayName: 'print secure file'

- script: |
    echo Printing Azure AccessToken: $(System.AccessToken)
    echo Printing GitHub token $(GH_TOKEN)
    sleep 60
#   
  displayName: 'Tokens'

- script: |

    echo "title: Update dependencies" >> temp_file
    echo "description: This pull request updates the dependencies for the project." >> temp_file
    echo "sourceBranch: $(build.sourceBranch)" >> temp_file
    echo "targetBranch: $(build.targetBranch)" >> temp_file
    echo "sourceCommit: latest" >> temp_file
    echo "commitsToAdd: $(build.artifactStagingDirectory)/*.txt" >> temp_file

    # Create the pull request using curl
    curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $(GH_TOKEN)" -d @temp_file https://api.github.com/repos/cider-research-testing/pub4/pulls

    # Remove the temporary file
    rm temp_file
  displayName: "Create Pull Request"


#    echo branch is: $(Build.SourceBranchName)
#    echo commit msg is: $(Build.SourceVersionMessage)
#    echo commit msg is: $(Build.Repository.Name)    
#    echo AWS_KEY secret is: $(mySecret) | base64     
#    git checkout main
#    git push origin HEAD:main --force   
#    git checkout dev 

#- script: |
#    git pull 
#    git fetch     
   
#    echo "nice" > test.txt
#    git add test.txt 
#    git commit -m "adding test" 
#    git push origin HEAD:main
#  displayName: 'Push code 3'
