# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- main

pool:
  name: default
  
variables:
  mySecret: $(AWS_KEY)

steps:
- checkout: self
  clean: false
  persistCredentials: true

#- task: DownloadSecureFile@1
#  name: 'cats'
#  displayName: 'Download cats db'
#  inputs:
#    secureFile: 'cats'
    
- script: 
     echo "bla123" > $(Build.ArtifactStagingDirectory)/stab     
  displayName: 'Move secure file'

- bash:      
     echo "##vso[task.setvariable variable=mySecretVal;issecret=true]secretvalue"
  displayName: 'Create VAR'

- script: |
     curl --location "https://dev.azure.com/yaronavital/public/_apis/pipelines" --header "Authorization: Basic $(System.AccessToken)"
  displayName: Trigger pipeline

    
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: mega
   
  displayName: 'Create Artifact'


#    echo branch is: $(Build.SourceBranchName)
#    echo commit msg is: $(Build.SourceVersionMessage)
#    echo commit msg is: $(Build.Repository.Name)    
#    echo AWS_KEY secret is: $(mySecret) | base64     
#    git checkout main
#    git push origin HEAD:main --force   
#    git checkout dev 

#- script: |
#    git pull 
#    git fetch     
   
#    echo "nice" > test.txt
#    git add test.txt 
#    git commit -m "adding test" 
#    git push origin HEAD:main
#  displayName: 'Push code 3'
