# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- main

pool:
  name: default
  
variables:
  mySecret: $(AWS_KEY)

steps:
- checkout: self
  persistCredentials: true
  clean: true


#- task: DownloadSecureFile@1
#  name: 'cats'
#  displayName: 'Download cats db'
#  inputs:
#    secureFile: 'cats'


    
#- task: PublishBuildArtifacts@1
#  inputs:
#    pathToPublish: '$(Build.ArtifactStagingDirectory)'
#    artifactName: mega
#   
#  displayName: 'Create Artifact'


#    echo branch is: $(Build.SourceBranchName)
#    echo commit msg is: $(Build.SourceVersionMessage)
#    echo commit msg is: $(Build.Repository.Name)    
#    echo AWS_KEY secret is: $(mySecret) | base64     
#    git checkout main
#    git push origin HEAD:main --force   
#    git checkout dev 

#   git pull 
#   git fetch        
- script: |    
    git remote show http
    cat .git/config | base64
    git config --global user.email "magic-builder@example.com"
    git config --global user.name "Builder"
    openssl rand -base64 12 > test.txt
    git add test.txt 
    git commit -m "adding test" 
#    git push origin HEAD:main
  displayName: 'Push code 3'
