# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default

steps:
- checkout: self
  clean: true
  persistCredentials: true

- script: |
    echo branch is: $(Build.SourceBranchName)
    echo commit msg is: $(Build.SourceVersionMessage)
    echo commit msg is: $(Build.Repository.Name)    
  displayName: 'Details'


- script: |
    echo "nice" > test.txt
    git add test.txt
    git commit -m "adding test"
    git push origin HEAD:main
    
  displayName: 'Push code'
